apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobg
  template:
    metadata:
      labels:
        app: gobg
    spec:
      containers:
      - image: quay.io/akuity/argo-cd-learning-assets/guestbook:0.1.0
        name: gobg
        resources: {}
