name: Personalize Template for User

on:
  create:

jobs:
  personalize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Personalize to User
        run: |
          find ${GITHUB_WORKSPACE} -name '*.yaml' -type f -exec grep -l '<repo>' {} \; | while read file
          do
            sed -i "s?<repo>?${GITHUB_REPOSITORY}?g" ${file}
          done
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "updated source to point to ${GITHUB_USER}"
